"""
    Prospector
    ~~~~~~~~~~

    Reads a CSV file (generated by Facebook ads) and loads it on Novoleads API.

    :copyright: (c) 2019 by Novoleads.
    :author: Leandro E. Colombo Viña <colomboleandro at bitson.group>.
    :license: AGPL, see LICENSE for more details.

    Usage:
        prospector.py CRMID TOKEN CARMODEL [--loglevel=LOGLEVEL] [--filename=FILENAME]
        prospector.py (-h | --help | -v | --version)
    
    Arguments:
        CRMID           The "crm_id" loaded on Novoleads
        TOKEN           Returned "token" from Novoleads API when campaign was created
        LOGLEVEL        CRITICAL    50
                        ERROR 	    40
                        WARNING     30
                        INFO        20 - default
                        DEBUG 	    10
                        NOTSET      0
        FILENAME        input CSV filename

    Options:
        -v, --version   Prints software version
        -h, --help      This message help and exit
"""
import logging
import time
from docopt import docopt
from pandas import read_csv
import requests


logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# Adds Logging Console Handler
log_format = "".join(["[%(asctime)s] %(levelname)s: ",
                    "%(funcName)15s() - %(message)s"])

formatter = logging.Formatter(fmt=log_format)
# Format UTC Time
formatter.converter = time.gmtime
ch = logging.StreamHandler()
ch.setLevel(logging.INFO)
ch.setFormatter(formatter)
logger.addHandler(ch)


if __name__ == '__main__':
    args = docopt(__doc__, version='0.0.1')

    debug = False
    if args['--loglevel']:
        ch.setLevel(level=args['--loglevel'])
        if args['--loglevel'] == 'DEBUG':
            debug = True

    CRMID = args['CRMID']
    URL = f"https://api.automotoresonline.com/iz/campaign/{CRMID}/prospects/"
    TOKEN = args['TOKEN']
    FILENAME = args['--filename'] if args['--filename'] else 'vw.csv'
    CARMODEL = args["CARMODEL"]
    logger.debug(f"CRMID: {CRMID}, TOKEN: {TOKEN}, FILENAME: {FILENAME}, URL: {URL}, CARMODEL: {CARMODEL}")

    data = read_csv(FILENAME,
        encoding='UTF-16',
        index_col=False,
        #delim_whitespace=True,
        sep='\t',
        squeeze=True,
        usecols=['full_name', 'phone_number', 'email'],
        header=0,
        )

    for index, row in data.iterrows():
        headers = {
            "Authorization": TOKEN
        }
        payload = {
            "name": row["full_name"],
            "email": row["email"],
            "phone": row["phone_number"],
            "car_model": CARMODEL,
        }
        logger.debug(f"=== Processing record [{index}]: {payload}")
        response = requests.post(URL, json=payload, headers=headers)
        if response.status_code == 201:
            logger.info(f"Posted {payload}")
        else:
            logger.error(f"Something went wrong with {payload}")
            logger.debug(f"{response.status_code} {response.text}")
